services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: finflow
      POSTGRES_USER: finflow
      POSTGRES_PASSWORD: finflow
    ports:
      - "5432:5432"
    volumes:
      - finflow-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finflow -d finflow"]
      interval: 5s
      timeout: 5s
      retries: 10

  s3server:
    image: minio/minio:latest
    container_name: finflow-s3server
    ports:
      - "9000:9000"
      - "9009:9009"
    environment:
      MINIO_ROOT_USER: local_env
      MINIO_ROOT_PASSWORD: local_env
    command: 'server --console-address ":9009" /data'
    volumes:
      - finflow-minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 20

  init-s3server-finflow-documents-bucked:
    image: garland/aws-cli-docker
    container_name: finflow-init-s3-bucket
    depends_on:
      s3server:
        condition: service_healthy
    environment:
      AWS_ACCESS_KEY_ID: local_env
      AWS_SECRET_ACCESS_KEY: local_env
      AWS_DEFAULT_REGION: eu-central-1
    command: >
      sh -c "aws --endpoint-url=http://s3server:9000 s3 mb s3://finflow-documents || true"

  localstack:
    image: localstack/localstack:4.4.0
    container_name: finflow-localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: sqs
      AWS_DEFAULT_REGION: eu-central-1
      DEBUG: "1"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:4566/_localstack/health || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 20

  init-localstack-sqs:
    image: amazon/aws-cli:latest
    container_name: finflow-init-sqs
    depends_on:
      localstack:
        condition: service_healthy
    entrypoint: []
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: eu-central-1
    command:
      - /bin/sh
      - -c
      - |
        aws --endpoint-url=http://localstack:4566 sqs create-queue --queue-name expense-submitted-events || true
        aws --endpoint-url=http://localstack:4566 sqs create-queue --queue-name expense-submitted-events-dlq || true

  finflow-app:
    build:
      context: ../../finflow-app
      dockerfile: Dockerfile
    container_name: finflow-app
    depends_on:
      postgres:
        condition: service_healthy
      s3server:
        condition: service_healthy
      init-s3server-finflow-documents-bucked:
        condition: service_completed_successfully
      localstack:
        condition: service_healthy
      init-localstack-sqs:
        condition: service_completed_successfully
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/finflow
      SPRING_DATASOURCE_USERNAME: finflow
      SPRING_DATASOURCE_PASSWORD: finflow

      APP_AWS_REGION: eu-central-1
      APP_AWS_S3_ENDPOINT: http://s3server:9000
      APP_AWS_S3_ACCESS_KEY: local_env
      APP_AWS_S3_ACCESS_SECRET: local_env
      APP_AWS_S3_FORCE_PATH_STYLE: "true"
      APP_AWS_S3_DOCUMENTS_BUCKET: finflow-documents

      APP_AWS_SQS_ENDPOINT: http://localstack:4566
      APP_AWS_SQS_EXPENSE_SUBMITTED_QUEUE_NAME: expense-submitted-events
    ports:
      - "8080:8080"
volumes:
  finflow-postgres-data:
  finflow-minio-data:
