spring:
  application:
    name: finflow-app
  datasource:
    url: jdbc:postgresql://localhost:5432/finflow
    username: finflow
    password: finflow
  jpa:
    hibernate:
      ddl-auto: validate

app:
  aws:
    region: eu-central-1
    s3:
      endpoint: http://localhost:9000
      access-key: local_env
      access-secret: local_env
      force-path-style: true
      documents-bucket: finflow-documents
    sqs:
      endpoint: http://localhost:4566
      access-key: test
      access-secret: test
      expense-submitted-queue-name: expense-submitted-events
      polling-delay-ms: 5000

  ledger:
    accounts:
      expense-account-id: 00000000-0000-0000-0000-000000000301
      employee-payable-account-id: 00000000-0000-0000-0000-000000000302

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
      first-name: admin
    filter:
      create: All tasks

logging:
  pattern:
    level: "%5p [correlationId:%X{correlationId:-}]"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: finflow-app
      environment: local
