{
 "title": "FinFlow Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Application Up",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "up{job=\"finflow-app\"}"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 0, "w": 9, "h": 4 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"finflow-app\"}[1m]))"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "x": 15, "y": 0, "w": 9, "h": 4 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"finflow-app\"})"
    }
   ]
  },
  {
   "title": "Outbox Pending",
   "type": "stat",
   "gridPos": { "x": 0, "y": 4, "w": 6, "h": 4 },
   "targets": [
    { "expr": "finflow_outbox_events_pending" }
   ]
  },
  {
   "title": "SQS Received",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 4, "w": 9, "h": 4 },
   "targets": [
    {
     "expr": "rate(finflow_sqs_messages_received_total[1m])"
    }
   ]
  },
  {
   "title": "Reports Jobs Failed",
   "type": "stat",
   "gridPos": { "x": 15, "y": 4, "w": 9, "h": 4 },
   "targets": [
    { "expr": "finflow_reports_jobs_failed" }
   ]
  }
 ]
}