ALTER TABLE expense_claims ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE report_jobs ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE outbox_events ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE ledger_transactions ADD COLUMN version BIGINT NOT NULL DEFAULT 0;